name: Build
on:
  push:
    tags:
        - '*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
              name: Checkout
            - uses: actions/setup-node@v3
              name: Setup Node.js
              with:
                  node-version: 18.16.0
            - name: Install g++-multilib
              run: sudo apt-get install g++-multilib
              if: matrix.os == 'ubuntu-latest'
            - name: Install dependencies
              run: npm i
            - name: Publish
              run: npm run publish
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}